{% set name = "rtoml" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rtoml-{{ version }}.tar.gz
  sha256: 113f2e133d152d9424269c475b4a7d0679987078b543e88fcb16c870dc2c460d

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=0.13,<0.14
    - pip
  run:
    - python

test:
  source_files:
    - tests
    - ./example.py
  imports:
    - rtoml
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not test_datetime_invalid" tests  # [python_impl == 'pypy']
    - pytest -vvv --capture=tee-sys -k tests  # [python_impl != 'pypy']
  requires:
    - dirty-equals ==0.5.0
    - pip
    - pytest >=7.1.2
    - pytest-pretty ==0.0.1
    - pytest-speed ==0.3.2

about:
  home: https://github.com/samuelcolvin/rtoml
  license: MIT
  license_file: LICENSE
  summary: A fast TOML library for python implemented in rust. 

extra:
  recipe-maintainers:
    - thewchan
